version: '3.8'
services:
  whispad:
    build: .
    ports:
      - "5037:5037"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - LMSTUDIO_HOST=${LMSTUDIO_HOST:-127.0.0.1}
      - LMSTUDIO_PORT=${LMSTUDIO_PORT:-1234}
      - OLLAMA_HOST=${OLLAMA_HOST:-127.0.0.1}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
      - BACKEND_PORT=8000
      - CORS_ORIGINS=https://localhost:5037,https://127.0.0.1:5037
      - DEBUG=False
    volumes:
      - ./logs:/var/log/nginx
      - ./saved_notes:/app/saved_notes
      - ./whisper-cpp-models:/app/whisper-cpp-models
      - ./users.json:/app/users.json
      - ./server_config.json:/app/server_config.json
    restart: unless-stopped
