version: '3.8'
services:
  whispad:
    build: .
    ports:
      - "5037:5037"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN:-}


      - LMSTUDIO_HOST=${LMSTUDIO_HOST:-127.0.0.1}
      - LMSTUDIO_PORT=${LMSTUDIO_PORT:-1234}
      - OLLAMA_HOST=${OLLAMA_HOST:-127.0.0.1}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}

      - MULTI_USER=${MULTI_USER:-true}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}

      - BACKEND_PORT=8000
      - CORS_ORIGINS=https://localhost:5037,https://127.0.0.1:5037
      - DEBUG=False
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      
    depends_on:
      - db
    volumes:
      - ./logs:/var/log/nginx
      - ./saved_notes:/app/saved_notes
      - ./saved_audios:/app/saved_audios
      - ./whisper-cpp-models:/app/whisper-cpp-models
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
