version: '3.8'
services:
  whispad:
    build:
      context: .
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    ports:
      - "5037:5037"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - LMSTUDIO_HOST=${LMSTUDIO_HOST:-127.0.0.1}
      - LMSTUDIO_PORT=${LMSTUDIO_PORT:-1234}
      - OLLAMA_HOST=${OLLAMA_HOST:-127.0.0.1}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
      - MULTI_USER=${MULTI_USER:-true}
      - BACKEND_PORT=8000
      - CORS_ORIGINS=https://localhost:5037,https://127.0.0.1:5037
      - DEBUG=False
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - ./logs:/var/log/nginx
      - ./saved_notes:/app/saved_notes
      - ./whisper-cpp-models:/app/whisper-cpp-models
      - ./data:/app/data
    user: "${PUID:-1000}:${PGID:-1000}"
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
